version: '3'

services:
  
  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception
    env_file: env/.env_db
    restart: unless-stopped
    expose:
      - "3306"

  wordpress:
    image: wordpress
    container_name: wordpress
    build: requirements/wordpress
    volumes:
       - www-data:/var/www/html/
    depends_on:
      - mariadb
    networks:
      - inception
    env_file: env/.env_wp
    restart: unless-stopped
    expose:
      - "9000"
  
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - www-data:/var/www/html
    depends_on:
      - ntp
      - wordpress
      - adminer
    networks:
      - inception
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    build: requirements/bonus/redis
    ports: 
      - "6379:6379"
    depends_on:
      - wordpress
    networks:
      - inception
    restart: unless-stopped

  ftp_server:
    image: ftp_server
    container_name: ftp_server
    build: requirements/bonus/ftp_server
    ports:
       - "21:21"
       - "5000-5010:5000-5010"
    depends_on:
       - wordpress
    volumes:
      - www-data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    env_file: env/.env_ftp
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    build: requirements/bonus/adminer
    volumes:
      - www-data:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  ntp:
    image: ntp
    container_name: ntp
    build: requirements/bonus/ntp
    ports:
      - "123:123/udp"
    networks:
      - inception
    restart: unless-stopped

  website:
    image: website
    container_name: website
    build: requirements/bonus/website
    networks:
      - inception
    ports:
      - "7777:7777"
    restart: unless-stopped

networks:
  inception:

volumes:
  db-data:
  www-data:
