# Specify the parent image from which we build
FROM Alpine

# Set the working directory
WORKDIR

# Copy files from your host to your current working directory
COPY

# Build the application with cmake
RUN 
# example: mkdir /app/hello_zed_src/build && cd /app/hello_zed_src/build && \
 #   cmake -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs \
  #    -DCMAKE_CXX_FLAGS="-Wl,--allow-shlib-undefined" .. && \
   # make`

# Run the application
CMD 
